---
- name: Setup Docker na VM
  hosts: taskflow_server
  become: yes
  tasks:
    - name: Atualizar apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar dependências
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Instalar Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Adicionar usuário ubuntu ao grupo docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Garantir que Docker está rodando
      service:
        name: docker
        state: started
        enabled: yes

    - name: Testar Docker
      command: docker --version
      register: docker_version

    - name: Mostrar versão do Docker
      debug:
        var: docker_version.stdout
